export interface Quote {
    id: number,    
    equipmentId: number,
    commodityId: number,
    weight: number,
    cargoValue: string,
    temperature: string,
    pieces: number,
    cargoTypeId: string,
    isHazmat: boolean,
    hazmatName: string,
    hazmatClass: string,
    hazmatUN: string,
    companyId: number,
    contactId: number,
    createdAt: number,
    quoteId: number,
    updatedAt: number,
    userId: number,
}